spring.datasource.url=jdbc:postgresql://ballast.proxy.rlwy.net:49633/railway
spring.datasource.username=postgres
spring.datasource.password=ylQFKAOHIAJlNvOciiXAPbFuPThxzTxX
spring.datasource.driver-class-name=org.postgresql.Driver
server.port=3000

# === Hibernate / JPA ===
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# === News API ===
news.api.key=80880b6ccb1859033d4d0df5064fb12e
