server:
  port: ${PORT:8080}

spring:
  application:
    name: website-project-ai-java
  cache:
    type: caffeine
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:}
    username: ${SPRING_DATASOURCE_USERNAME:}
    password: ${SPRING_DATASOURCE_PASSWORD:}
    hikari:
      maximum-pool-size: ${SPRING_DATASOURCE_MAX_POOL_SIZE:10}
      minimum-idle: ${SPRING_DATASOURCE_MIN_IDLE:2}
      connection-timeout: 30000
      validation-timeout: 5000
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        format_sql: true
  jackson:
    serialization:
      write-dates-as-timestamps: false

news:
  api:
    base-url: https://newsapi.org/v2
    key: ${NEWS_API_KEY:}

management:
  endpoints:
    web:
      exposure:
        include: health,info
